/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRow: typeof import('element-plus/es')['ElRow']
    IEpAlipay: typeof import('~icons/ep/alipay')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpHide: typeof import('~icons/ep/hide')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpUpload: typeof import('~icons/ep/upload')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IEpView: typeof import('~icons/ep/view')['default']
    IUiwAlipay: typeof import('~icons/uiw/alipay')['default']
    IUiwBell: typeof import('~icons/uiw/bell')['default']
    IUiwFolder: typeof import('~icons/uiw/folder')['default']
    IUiwLock: typeof import('~icons/uiw/lock')['default']
    IUiwNotification: typeof import('~icons/uiw/notification')['default']
    IUiwSearch: typeof import('~icons/uiw/search')['default']
    IUiwTimeO: typeof import('~icons/uiw/time-o')['default']
    IUiwUpload: typeof import('~icons/uiw/upload')['default']
    IUiwUser: typeof import('~icons/uiw/user')['default']
    IUiwWeibo: typeof import('~icons/uiw/weibo')['default']
    IUiwWeixin: typeof import('~icons/uiw/weixin')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
